export enum MessageCodeModel{
  REGISTRATION_SUCCESS,
  EMAIL_IN_USE,
  UNEXPECTED_ERROR,
  EMAIL_NOT_REGISTERED,
  NOT_ACTIVATED_EMAIL,
  LOGIN_SUCCESS,
  EMAIL_CONFIRMATION_SUCCESS,
  EMAIL_CONFIRMATION_ERROR
}
